export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  USUARIOS: '/usuarios',
  PROVEEDORES: '/proveedores',
  CLIENTES: '/clientes',
  PRODUCTOS: '/productos',
  COSTOS: '/costos',
  INSUMOS: '/insumos',
  FORMULAS: '/formulas',
  PRODUCCION: '/produccion',
  STOCK: '/stock',
  STOCKMATERIAPRIMA: '/stockMateriaPrima',
  TRAZABILIDAD: '/trazabilidad',
  SILOS: '/silos',
  ORDENES: '/Ordenes',
} as const;
