export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  DASHBOARD_OPERATIVO: '/operativo',
  USUARIOS: '/usuarios',
  PROVEEDORES: '/proveedores',
  CLIENTES: '/clientes',
  PRODUCTOS: '/productos',
  COSTOS: '/costos',
  MOVIMIENTOS_FINANCIEROS: '/costos/movimientos',
  ESTADOS_FINANCIEROS: '/estados-financieros',
  TESORERIA: '/tesoreria',
  INSUMOS: '/insumos',
  FORMULAS: '/formulas',
  PRODUCCION: '/produccion',
  STOCK: '/stock',
  ALERTAS: '/alertas',
  STOCKMATERIAPRIMA: '/stockMateriaPrima',
  TRAZABILIDAD: '/trazabilidad',
  SILOS: '/silos',
  ORDENES: '/ordenes',
  ORDENES_SALIDA: '/ordenes-salida',
} as const;
